spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sayonecourse
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  hikari:
    maximumPoolSize: 10
    idleTimeout: 30000

debug: true
